services:
  - type: web
    name: library-backend
    runtime: python
    pythonVersion: "3.12.0"
    rootDir: library_backend
    buildCommand: "pip install --upgrade -r ../requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn library_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 60"
    envVars:
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: library-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://ipt-group-pit-psi.vercel.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://ipt-group-pit-psi.vercel.app
      - key: REQUIRE_EMAIL_VERIFICATION
        value: True

databases:
  - name: library-db
    databaseName: library_db
    user: library_user